//package com;
import com.learn.droolsdemo.domain.Message

rule "Hello World"
agenda-group "message-group"
dialect "mvel"
when
m : Message(status.equals(Message.HELLO), message : message )
then
System.out.println( message);
modify ( m ) { message = "Goodbye cruel world",status = Message.GOODBYE };
end

rule "Good Bye"
agenda-group "message-group-2"
dialect "java"
when
Message( status == Message.GOODBYE, message : message )
then
System.out.println( message );
end